services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        USER_ID: ${HOST_UID:-1000}
        GROUP_ID: ${HOST_GID:-1000}
    environment:
      APP_ENV: ${APP_ENV:-local}
      APP_DEBUG: ${APP_DEBUG:-true}
    volumes:
      - ./:/var/www/html
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - bulknet

  queue:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: php artisan queue:work --tries=3 --backoff=5
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    depends_on:
      - app
    networks:
      - bulknet

  scheduler:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: php artisan schedule:work
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    depends_on:
      - app
    networks:
      - bulknet

  web:
    image: nginx:1.27-alpine
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - bulknet

  node:
    image: node:22-alpine
    working_dir: /app
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port ${VITE_PORT:-5173}"
    volumes:
      - ./:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "${VITE_PORT:-5173}:5173"
    depends_on:
      - app
    networks:
      - bulknet

networks:
  bulknet:
    driver: bridge
